baseURL = 'https://hosting-netlify-decap-cms.netlify.app/'
languageCode = 'en-us'
title = 'Hosting Test - Netlify with Decap CMS'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    min = "0.147.1"
