publish_mode: editorial_workflow
media_folder: assets/images/uploads
public_folder: images/uploads
backend:
  name: git-gateway
  branch: main
collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: string
      - label: Images
        name: images
        widget: list
        fields:
          - {name: path, label: Image, widget: image}
          - {name: alt, label: Alt, widget: string}
